/***********************************************************************/
/*                                                                     */
/*  FILE        :CMotor.hpp                                            */
/*  DATE        :Jul 04, 2020                                          */
/*  DESCRIPTION :モータークラス                                        */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#ifndef _CMOTOR_HPP__
#define _CMOTOR_HPP__

#include <Arduino.h>

/***********************************************************************/
/*                         モーター駆動関数                            */
/***********************************************************************/
#define DUTY_RESOLUTION 100    // モーター制御のデューティ比の分解能
#define FILT_FREQ 100            //PID制御の周波数[hz] 

#define PWM_RESOLUTION 16000   // マイコンのPWM波形1周期の分解能
/*     PIN設定    */
#define MOTOR_AIN1_PIN 6
#define MOTOR_AIN2_PIN 7
#define MOTOR_PWMA_PIN 9
#define MOTOR_BIN1_PIN 8
#define MOTOR_BIN2_PIN A0
#define MOTOR_PWMB_PIN 10

class CMotor
{
public:
  CMotor(void);
  void driveMotors(int32_t dutyR, int32_t dutyL);
  void stopMotors(void);
private:
};


#endif  // _CMOTOR_HPP__
